version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install
      - yum install -y jq

  pre_build:
    commands:
      - echo "Fetching secrets from AWS Secrets Manager"
      - ENV_SECRET=$(aws secretsmanager get-secret-value --secret-id miniFinanceEnvVars --query SecretString --output text --region us-east-1)
      - echo "$ENV_SECRET" | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env

  build:
    commands:
      - echo "Zipping app with .env file"
      - zip -r deploy.zip . -x "*.git*" -x "node_modules/*"

artifacts:
  files:
    - deploy.zip
